[project]
name = "tuilip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "caetanogenete@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "more-itertools>=11.1.0",
    "rich>=15.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = true

[dependency-groups]
dev = [
    "mypy>=2.3.0",
    "pyright>=1.1.411",
    "pytest>=9.0.3",
    "ruff>=0.15.16",
]

[tool.mypy]
allow_redefinition = true
exclude = [
    "^src/tuilip/input/win32.py",
    "^src/tuilip/input/posix.py"
]

[tool.pyright]
typeCheckingMode = "strict"
reportUnnecessaryTypeIgnoreComment = true

exclude = [
	".venv",
	"**/__pycache__",
    "src/tuilip/input/win32.py",
    "src/tuilip/input/posix.py"
]

[tool.ruff.lint]

ignore = ["E741"]
